// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetAPIUserapiSystemSmets2PeriodicDataSystemIDReader is a Reader for the GetAPIUserapiSystemSmets2PeriodicDataSystemID structure.
type GetAPIUserapiSystemSmets2PeriodicDataSystemIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIUserapiSystemSmets2PeriodicDataSystemIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIUserapiSystemSmets2PeriodicDataSystemIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetAPIUserapiSystemSmets2PeriodicDataSystemIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetAPIUserapiSystemSmets2PeriodicDataSystemIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAPIUserapiSystemSmets2PeriodicDataSystemIDOK creates a GetAPIUserapiSystemSmets2PeriodicDataSystemIDOK with default headers values
func NewGetAPIUserapiSystemSmets2PeriodicDataSystemIDOK() *GetAPIUserapiSystemSmets2PeriodicDataSystemIDOK {
	return &GetAPIUserapiSystemSmets2PeriodicDataSystemIDOK{}
}

/*
GetAPIUserapiSystemSmets2PeriodicDataSystemIDOK describes a response with status code 200, with default header values.

Periodic energy data retrieved
*/
type GetAPIUserapiSystemSmets2PeriodicDataSystemIDOK struct {
	Payload *GetAPIUserapiSystemSmets2PeriodicDataSystemIDOKBody
}

// IsSuccess returns true when this get Api userapi system smets2 periodic data system Id o k response has a 2xx status code
func (o *GetAPIUserapiSystemSmets2PeriodicDataSystemIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api userapi system smets2 periodic data system Id o k response has a 3xx status code
func (o *GetAPIUserapiSystemSmets2PeriodicDataSystemIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api userapi system smets2 periodic data system Id o k response has a 4xx status code
func (o *GetAPIUserapiSystemSmets2PeriodicDataSystemIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api userapi system smets2 periodic data system Id o k response has a 5xx status code
func (o *GetAPIUserapiSystemSmets2PeriodicDataSystemIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api userapi system smets2 periodic data system Id o k response a status code equal to that given
func (o *GetAPIUserapiSystemSmets2PeriodicDataSystemIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api userapi system smets2 periodic data system Id o k response
func (o *GetAPIUserapiSystemSmets2PeriodicDataSystemIDOK) Code() int {
	return 200
}

func (o *GetAPIUserapiSystemSmets2PeriodicDataSystemIDOK) Error() string {
	return fmt.Sprintf("[GET /api/userapi/system/smets2-periodic-data/{systemId}][%d] getApiUserapiSystemSmets2PeriodicDataSystemIdOK  %+v", 200, o.Payload)
}

func (o *GetAPIUserapiSystemSmets2PeriodicDataSystemIDOK) String() string {
	return fmt.Sprintf("[GET /api/userapi/system/smets2-periodic-data/{systemId}][%d] getApiUserapiSystemSmets2PeriodicDataSystemIdOK  %+v", 200, o.Payload)
}

func (o *GetAPIUserapiSystemSmets2PeriodicDataSystemIDOK) GetPayload() *GetAPIUserapiSystemSmets2PeriodicDataSystemIDOKBody {
	return o.Payload
}

func (o *GetAPIUserapiSystemSmets2PeriodicDataSystemIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetAPIUserapiSystemSmets2PeriodicDataSystemIDOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIUserapiSystemSmets2PeriodicDataSystemIDUnauthorized creates a GetAPIUserapiSystemSmets2PeriodicDataSystemIDUnauthorized with default headers values
func NewGetAPIUserapiSystemSmets2PeriodicDataSystemIDUnauthorized() *GetAPIUserapiSystemSmets2PeriodicDataSystemIDUnauthorized {
	return &GetAPIUserapiSystemSmets2PeriodicDataSystemIDUnauthorized{}
}

/*
GetAPIUserapiSystemSmets2PeriodicDataSystemIDUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetAPIUserapiSystemSmets2PeriodicDataSystemIDUnauthorized struct {
}

// IsSuccess returns true when this get Api userapi system smets2 periodic data system Id unauthorized response has a 2xx status code
func (o *GetAPIUserapiSystemSmets2PeriodicDataSystemIDUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api userapi system smets2 periodic data system Id unauthorized response has a 3xx status code
func (o *GetAPIUserapiSystemSmets2PeriodicDataSystemIDUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api userapi system smets2 periodic data system Id unauthorized response has a 4xx status code
func (o *GetAPIUserapiSystemSmets2PeriodicDataSystemIDUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api userapi system smets2 periodic data system Id unauthorized response has a 5xx status code
func (o *GetAPIUserapiSystemSmets2PeriodicDataSystemIDUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api userapi system smets2 periodic data system Id unauthorized response a status code equal to that given
func (o *GetAPIUserapiSystemSmets2PeriodicDataSystemIDUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get Api userapi system smets2 periodic data system Id unauthorized response
func (o *GetAPIUserapiSystemSmets2PeriodicDataSystemIDUnauthorized) Code() int {
	return 401
}

func (o *GetAPIUserapiSystemSmets2PeriodicDataSystemIDUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/userapi/system/smets2-periodic-data/{systemId}][%d] getApiUserapiSystemSmets2PeriodicDataSystemIdUnauthorized ", 401)
}

func (o *GetAPIUserapiSystemSmets2PeriodicDataSystemIDUnauthorized) String() string {
	return fmt.Sprintf("[GET /api/userapi/system/smets2-periodic-data/{systemId}][%d] getApiUserapiSystemSmets2PeriodicDataSystemIdUnauthorized ", 401)
}

func (o *GetAPIUserapiSystemSmets2PeriodicDataSystemIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIUserapiSystemSmets2PeriodicDataSystemIDNotFound creates a GetAPIUserapiSystemSmets2PeriodicDataSystemIDNotFound with default headers values
func NewGetAPIUserapiSystemSmets2PeriodicDataSystemIDNotFound() *GetAPIUserapiSystemSmets2PeriodicDataSystemIDNotFound {
	return &GetAPIUserapiSystemSmets2PeriodicDataSystemIDNotFound{}
}

/*
GetAPIUserapiSystemSmets2PeriodicDataSystemIDNotFound describes a response with status code 404, with default header values.

System ID not found
*/
type GetAPIUserapiSystemSmets2PeriodicDataSystemIDNotFound struct {
}

// IsSuccess returns true when this get Api userapi system smets2 periodic data system Id not found response has a 2xx status code
func (o *GetAPIUserapiSystemSmets2PeriodicDataSystemIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api userapi system smets2 periodic data system Id not found response has a 3xx status code
func (o *GetAPIUserapiSystemSmets2PeriodicDataSystemIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api userapi system smets2 periodic data system Id not found response has a 4xx status code
func (o *GetAPIUserapiSystemSmets2PeriodicDataSystemIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api userapi system smets2 periodic data system Id not found response has a 5xx status code
func (o *GetAPIUserapiSystemSmets2PeriodicDataSystemIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api userapi system smets2 periodic data system Id not found response a status code equal to that given
func (o *GetAPIUserapiSystemSmets2PeriodicDataSystemIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get Api userapi system smets2 periodic data system Id not found response
func (o *GetAPIUserapiSystemSmets2PeriodicDataSystemIDNotFound) Code() int {
	return 404
}

func (o *GetAPIUserapiSystemSmets2PeriodicDataSystemIDNotFound) Error() string {
	return fmt.Sprintf("[GET /api/userapi/system/smets2-periodic-data/{systemId}][%d] getApiUserapiSystemSmets2PeriodicDataSystemIdNotFound ", 404)
}

func (o *GetAPIUserapiSystemSmets2PeriodicDataSystemIDNotFound) String() string {
	return fmt.Sprintf("[GET /api/userapi/system/smets2-periodic-data/{systemId}][%d] getApiUserapiSystemSmets2PeriodicDataSystemIdNotFound ", 404)
}

func (o *GetAPIUserapiSystemSmets2PeriodicDataSystemIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*
GetAPIUserapiSystemSmets2PeriodicDataSystemIDOKBody get API userapi system smets2 periodic data system ID o k body
swagger:model GetAPIUserapiSystemSmets2PeriodicDataSystemIDOKBody
*/
type GetAPIUserapiSystemSmets2PeriodicDataSystemIDOKBody struct {

	// history
	History []*GetAPIUserapiSystemSmets2PeriodicDataSystemIDOKBodyHistoryItems0 `json:"history"`
}

// Validate validates this get API userapi system smets2 periodic data system ID o k body
func (o *GetAPIUserapiSystemSmets2PeriodicDataSystemIDOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateHistory(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetAPIUserapiSystemSmets2PeriodicDataSystemIDOKBody) validateHistory(formats strfmt.Registry) error {
	if swag.IsZero(o.History) { // not required
		return nil
	}

	for i := 0; i < len(o.History); i++ {
		if swag.IsZero(o.History[i]) { // not required
			continue
		}

		if o.History[i] != nil {
			if err := o.History[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getApiUserapiSystemSmets2PeriodicDataSystemIdOK" + "." + "history" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("getApiUserapiSystemSmets2PeriodicDataSystemIdOK" + "." + "history" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this get API userapi system smets2 periodic data system ID o k body based on the context it is used
func (o *GetAPIUserapiSystemSmets2PeriodicDataSystemIDOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateHistory(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetAPIUserapiSystemSmets2PeriodicDataSystemIDOKBody) contextValidateHistory(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.History); i++ {

		if o.History[i] != nil {
			if err := o.History[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getApiUserapiSystemSmets2PeriodicDataSystemIdOK" + "." + "history" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("getApiUserapiSystemSmets2PeriodicDataSystemIdOK" + "." + "history" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetAPIUserapiSystemSmets2PeriodicDataSystemIDOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetAPIUserapiSystemSmets2PeriodicDataSystemIDOKBody) UnmarshalBinary(b []byte) error {
	var res GetAPIUserapiSystemSmets2PeriodicDataSystemIDOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
GetAPIUserapiSystemSmets2PeriodicDataSystemIDOKBodyHistoryItems0 get API userapi system smets2 periodic data system ID o k body history items0
swagger:model GetAPIUserapiSystemSmets2PeriodicDataSystemIDOKBodyHistoryItems0
*/
type GetAPIUserapiSystemSmets2PeriodicDataSystemIDOKBodyHistoryItems0 struct {

	// consumption
	Consumption int64 `json:"consumption,omitempty"`

	// timestamp
	// Format: date-time
	Timestamp strfmt.DateTime `json:"timestamp,omitempty"`

	// type
	// Enum: [ELECTRICITY GAS_ENERGY]
	Type string `json:"type,omitempty"`
}

// Validate validates this get API userapi system smets2 periodic data system ID o k body history items0
func (o *GetAPIUserapiSystemSmets2PeriodicDataSystemIDOKBodyHistoryItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateTimestamp(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetAPIUserapiSystemSmets2PeriodicDataSystemIDOKBodyHistoryItems0) validateTimestamp(formats strfmt.Registry) error {
	if swag.IsZero(o.Timestamp) { // not required
		return nil
	}

	if err := validate.FormatOf("timestamp", "body", "date-time", o.Timestamp.String(), formats); err != nil {
		return err
	}

	return nil
}

var getApiUserapiSystemSmets2PeriodicDataSystemIdOKBodyHistoryItems0TypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["ELECTRICITY","GAS_ENERGY"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		getApiUserapiSystemSmets2PeriodicDataSystemIdOKBodyHistoryItems0TypeTypePropEnum = append(getApiUserapiSystemSmets2PeriodicDataSystemIdOKBodyHistoryItems0TypeTypePropEnum, v)
	}
}

const (

	// GetAPIUserapiSystemSmets2PeriodicDataSystemIDOKBodyHistoryItems0TypeELECTRICITY captures enum value "ELECTRICITY"
	GetAPIUserapiSystemSmets2PeriodicDataSystemIDOKBodyHistoryItems0TypeELECTRICITY string = "ELECTRICITY"

	// GetAPIUserapiSystemSmets2PeriodicDataSystemIDOKBodyHistoryItems0TypeGASENERGY captures enum value "GAS_ENERGY"
	GetAPIUserapiSystemSmets2PeriodicDataSystemIDOKBodyHistoryItems0TypeGASENERGY string = "GAS_ENERGY"
)

// prop value enum
func (o *GetAPIUserapiSystemSmets2PeriodicDataSystemIDOKBodyHistoryItems0) validateTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, getApiUserapiSystemSmets2PeriodicDataSystemIdOKBodyHistoryItems0TypeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *GetAPIUserapiSystemSmets2PeriodicDataSystemIDOKBodyHistoryItems0) validateType(formats strfmt.Registry) error {
	if swag.IsZero(o.Type) { // not required
		return nil
	}

	// value enum
	if err := o.validateTypeEnum("type", "body", o.Type); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this get API userapi system smets2 periodic data system ID o k body history items0 based on context it is used
func (o *GetAPIUserapiSystemSmets2PeriodicDataSystemIDOKBodyHistoryItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetAPIUserapiSystemSmets2PeriodicDataSystemIDOKBodyHistoryItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetAPIUserapiSystemSmets2PeriodicDataSystemIDOKBodyHistoryItems0) UnmarshalBinary(b []byte) error {
	var res GetAPIUserapiSystemSmets2PeriodicDataSystemIDOKBodyHistoryItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
