// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAPIUserapiV2UserDetailSystemsParams creates a new GetAPIUserapiV2UserDetailSystemsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIUserapiV2UserDetailSystemsParams() *GetAPIUserapiV2UserDetailSystemsParams {
	return &GetAPIUserapiV2UserDetailSystemsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIUserapiV2UserDetailSystemsParamsWithTimeout creates a new GetAPIUserapiV2UserDetailSystemsParams object
// with the ability to set a timeout on a request.
func NewGetAPIUserapiV2UserDetailSystemsParamsWithTimeout(timeout time.Duration) *GetAPIUserapiV2UserDetailSystemsParams {
	return &GetAPIUserapiV2UserDetailSystemsParams{
		timeout: timeout,
	}
}

// NewGetAPIUserapiV2UserDetailSystemsParamsWithContext creates a new GetAPIUserapiV2UserDetailSystemsParams object
// with the ability to set a context for a request.
func NewGetAPIUserapiV2UserDetailSystemsParamsWithContext(ctx context.Context) *GetAPIUserapiV2UserDetailSystemsParams {
	return &GetAPIUserapiV2UserDetailSystemsParams{
		Context: ctx,
	}
}

// NewGetAPIUserapiV2UserDetailSystemsParamsWithHTTPClient creates a new GetAPIUserapiV2UserDetailSystemsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIUserapiV2UserDetailSystemsParamsWithHTTPClient(client *http.Client) *GetAPIUserapiV2UserDetailSystemsParams {
	return &GetAPIUserapiV2UserDetailSystemsParams{
		HTTPClient: client,
	}
}

/*
GetAPIUserapiV2UserDetailSystemsParams contains all the parameters to send to the API endpoint

	for the get API userapi v2 user detail systems operation.

	Typically these are written to a http.Request.
*/
type GetAPIUserapiV2UserDetailSystemsParams struct {

	/* Authorization.

	   Bearer token received from login
	*/
	Authorization string

	// SystemDetails.
	//
	// Default: true
	SystemDetails bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API userapi v2 user detail systems params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIUserapiV2UserDetailSystemsParams) WithDefaults() *GetAPIUserapiV2UserDetailSystemsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API userapi v2 user detail systems params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIUserapiV2UserDetailSystemsParams) SetDefaults() {
	var (
		systemDetailsDefault = bool(true)
	)

	val := GetAPIUserapiV2UserDetailSystemsParams{
		SystemDetails: systemDetailsDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get API userapi v2 user detail systems params
func (o *GetAPIUserapiV2UserDetailSystemsParams) WithTimeout(timeout time.Duration) *GetAPIUserapiV2UserDetailSystemsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API userapi v2 user detail systems params
func (o *GetAPIUserapiV2UserDetailSystemsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API userapi v2 user detail systems params
func (o *GetAPIUserapiV2UserDetailSystemsParams) WithContext(ctx context.Context) *GetAPIUserapiV2UserDetailSystemsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API userapi v2 user detail systems params
func (o *GetAPIUserapiV2UserDetailSystemsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API userapi v2 user detail systems params
func (o *GetAPIUserapiV2UserDetailSystemsParams) WithHTTPClient(client *http.Client) *GetAPIUserapiV2UserDetailSystemsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API userapi v2 user detail systems params
func (o *GetAPIUserapiV2UserDetailSystemsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the get API userapi v2 user detail systems params
func (o *GetAPIUserapiV2UserDetailSystemsParams) WithAuthorization(authorization string) *GetAPIUserapiV2UserDetailSystemsParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the get API userapi v2 user detail systems params
func (o *GetAPIUserapiV2UserDetailSystemsParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithSystemDetails adds the systemDetails to the get API userapi v2 user detail systems params
func (o *GetAPIUserapiV2UserDetailSystemsParams) WithSystemDetails(systemDetails bool) *GetAPIUserapiV2UserDetailSystemsParams {
	o.SetSystemDetails(systemDetails)
	return o
}

// SetSystemDetails adds the systemDetails to the get API userapi v2 user detail systems params
func (o *GetAPIUserapiV2UserDetailSystemsParams) SetSystemDetails(systemDetails bool) {
	o.SystemDetails = systemDetails
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIUserapiV2UserDetailSystemsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	// query param systemDetails
	qrSystemDetails := o.SystemDetails
	qSystemDetails := swag.FormatBool(qrSystemDetails)
	if qSystemDetails != "" {

		if err := r.SetQueryParam("systemDetails", qSystemDetails); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
